In [4]:
import numpy
import cv2

In [5]:
img = cv2.imread('smallgray.png',0)

In [6]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
mig = cv2.imread('smallgray.png',1)
mig

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [10]:
n = numpy.arange(9000)
s = n.reshape(300,30)
i = numpy.hstack((img,img,img))
x = numpy.hstack((i,i,i,i,i))
y = x.flip
my_img = cv2.imwrite("my_img.png",x)
s

array([[   0,    1,    2, ...,   27,   28,   29],
       [  30,   31,   32, ...,   57,   58,   59],
       [  60,   61,   62, ...,   87,   88,   89],
       ...,
       [8910, 8911, 8912, ..., 8937, 8938, 8939],
       [8940, 8941, 8942, ..., 8967, 8968, 8969],
       [8970, 8971, 8972, ..., 8997, 8998, 8999]])