In [1]:
import numpy
import cv2

In [2]:
img = cv2.imread('smallgray.png',0)
img


array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [3]:
arr = img

In [4]:
for i in arr:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [5]:
arr[:4]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
arr[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [13]:
a = arr[0:2,2:4]
a.shape()

TypeError: 'tuple' object is not callable

In [15]:
for i in arr.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]
